"""
build_fighter_profiles.py

Combine ufc_fighter_tott.csv with strictly-verified UFC fighter data
scraped from Wikipedia. Outputs Fighter_Profiles.csv.

Use --top-elo N to restrict scraping to the top N UFC fighters by peak Elo
(read from fighter_elo.csv; optionally regenerated by importing the
elo_rankings module first).
"""

from __future__ import annotations

import argparse
import importlib
import json
import re
import sys
import time
from pathlib import Path

import mwparserfromhell
import pandas as pd
import requests
from rapidfuzz import fuzz, process
from tqdm import tqdm
from unidecode import unidecode

WIKI_API = "https://en.wikipedia.org/w/api.php"
HEADERS = {"User-Agent": "UFCProfileBuilder/1.0 (johnmatthewdavenport@gmail.com)"}
MAX_RETRIES = 6
CACHE_DIR = Path(".wiki_cache")
CACHE_DIR.mkdir(exist_ok=True)

# ----- columns we keep from ufc_fighter_tott.csv -----
TOTT_KEEP = {
    "fighter_name": "name",
    "name": "name",
    "Fighter": "name",
    "Name": "name",
    "Height": "csv_height",
    "height": "csv_height",
    "HEIGHT": "csv_height",
    "Weight": "csv_weight",
    "weight": "csv_weight",
    "WEIGHT": "csv_weight",
    "Reach": "csv_reach",
    "reach": "csv_reach",
    "REACH": "csv_reach",
    "Stance": "csv_stance",
    "stance": "csv_stance",
    "STANCE": "csv_stance",
    "DOB": "csv_dob",
    "dob": "csv_dob",
    "Date_of_birth": "csv_dob",
}

# ----- wiki infobox fields we extract -----
INFOBOX_FIELDS = [
    "birth_name", "other_names", "birth_date", "birth_place",
    "nationality", "residence",
    "height", "height_ft", "height_in", "height_cm",
    "weight", "weight_lb", "weight_kg", "weight_class",
    "reach", "reach_in", "reach_cm",
    "stance",
    "style", "team", "trainer", "rank", "years_active",
    "fighting_out_of",
    "mma_kowin", "mma_subwin", "mma_decwin", "mma_dqwin",
    "mma_koloss", "mma_subloss", "mma_decloss", "mma_dqloss",
    "mma_draw", "mma_nc",
    "url", "sherdog",
]


def _cache_path(kind: str, key: str) -> Path:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", key)[:180]
    return CACHE_DIR / f"{kind}__{safe}.json"


def cached_get(kind, key, fetcher, refresh=False):
    path = _cache_path(kind, key)
    if path.exists() and not refresh:
        return json.loads(path.read_text(encoding="utf-8"))
    data = fetcher()
    path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
    return data


def wiki_get(params):
    """GET against the Wikipedia API with retry/backoff on 429 and 5xx."""
    backoff = 2.0
    last = None
    for _ in range(MAX_RETRIES):
        r = requests.get(WIKI_API, params=params, headers=HEADERS, timeout=30)
        last = r
        if r.status_code == 429 or r.status_code >= 500:
            wait = float(r.headers.get("Retry-After", backoff))
            time.sleep(wait)
            backoff = min(backoff * 2, 60)
            continue
        r.raise_for_status()
        return r.json()
    last.raise_for_status()
    return last.json()


def wiki_search(name, refresh=False):
    def _do():
        params = {
            "action": "query", "list": "search",
            "srsearch": f'"{name}" UFC mixed martial artist',
            "format": "json", "srlimit": 8,
        }
        return wiki_get(params).get("query", {}).get("search", [])
    return cached_get("search", name, _do, refresh)


def wiki_page(title, refresh=False):
    def _do():
        params = {
            "action": "query", "prop": "revisions|categories",
            "rvprop": "content", "rvslots": "main", "cllimit": "max",
            "titles": title, "format": "json", "redirects": 1,
        }
        data = wiki_get(params)
        pages = data.get("query", {}).get("pages", {})
        for _, page in pages.items():
            revs = page.get("revisions") or []
            cats = [c["title"] for c in page.get("categories", [])]
            return {
                "title": page.get("title"),
                "wikitext": revs[0]["slots"]["main"]["*"] if revs else "",
                "categories": cats,
            }
        return {"title": None, "wikitext": "", "categories": []}
    return cached_get("page", title, _do, refresh)


def normalize(s):
    return re.sub(r"[^a-z0-9]+", " ", unidecode(str(s)).lower()).strip()


def fuzzy_pick(query_name, candidates):
    if not candidates:
        return None
    titles = [c["title"] for c in candidates]
    norm_titles = [normalize(t) for t in titles]
    match = process.extractOne(normalize(query_name), norm_titles, scorer=fuzz.WRatio)
    if not match:
        return None
    _, score, idx = match
    if score < 70:
        return None
    return candidates[idx]


UFC_CATEGORY_PATTERNS = [
    r"Ultimate Fighting Championship",
    r"UFC ",
    r"American mixed martial artists",
    r"mixed martial artists",
]


def is_ufc_fighter(page):
    reasons = {"has_category": False, "has_infobox_ufc": False, "body_mentions_ufc": False}
    cats = " | ".join(page.get("categories", []))
    if any(re.search(p, cats, re.I) for p in UFC_CATEGORY_PATTERNS):
        reasons["has_category"] = True
    wikitext = page.get("wikitext", "") or ""
    code = mwparserfromhell.parse(wikitext)
    infobox_text = ""
    for tpl in code.filter_templates():
        if tpl.name.strip().lower().startswith("infobox martial artist"):
            infobox_text = str(tpl)
            break
    if infobox_text and re.search(r"\bUFC\b|Ultimate Fighting Championship", infobox_text, re.I):
        reasons["has_infobox_ufc"] = True
    if re.search(r"\bUFC\b|Ultimate Fighting Championship", wikitext, re.I):
        reasons["body_mentions_ufc"] = True
    return all(reasons.values()), reasons


def _strip(val):
    txt = mwparserfromhell.parse(val).strip_code(normalize=True, collapse=True)
    return re.sub(r"\s+", " ", txt).strip()


def parse_infobox(wikitext):
    code = mwparserfromhell.parse(wikitext)
    for tpl in code.filter_templates():
        if tpl.name.strip().lower().startswith("infobox martial artist"):
            data = {}
            if tpl.has("name"):
                data["wiki_name"] = _strip(str(tpl.get("name").value))
            for f in INFOBOX_FIELDS:
                if tpl.has(f):
                    data[f"wiki_{f}"] = _strip(str(tpl.get(f).value))
            return data
    return {}


FT_IN_RE = re.compile(r"(\d+)\s*(?:'|ft|\u2032)\s*(\d+(?:\.\d+)?)?\s*(?:\"|in|\u2033)?")
CM_RE = re.compile(r"(\d+(?:\.\d+)?)\s*cm", re.I)
LB_RE = re.compile(r"(\d+(?:\.\d+)?)\s*(?:lb|lbs|pounds)", re.I)
KG_RE = re.compile(r"(\d+(?:\.\d+)?)\s*kg", re.I)
IN_RE = re.compile(r"(\d+(?:\.\d+)?)\s*(?:\"|in|inches|\u2033)", re.I)


def parse_height(text):
    if not text:
        return None, None
    cm = imperial = None
    m = FT_IN_RE.search(text)
    if m:
        ft = int(m.group(1))
        inch = float(m.group(2)) if m.group(2) else 0.0
        imperial = f"{ft}'{inch:g}\""
        cm = round(ft * 30.48 + inch * 2.54, 1)
    m2 = CM_RE.search(text)
    if m2:
        cm = float(m2.group(1))
        if not imperial:
            total_in = cm / 2.54
            ft = int(total_in // 12)
            inch = round(total_in - ft * 12, 1)
            imperial = f"{ft}'{inch:g}\""
    return imperial, (str(cm) if cm is not None else None)


def parse_weight(text):
    if not text:
        return None, None
    lb = kg = None
    m = LB_RE.search(text)
    if m: lb = float(m.group(1))
    m2 = KG_RE.search(text)
    if m2: kg = float(m2.group(1))
    if lb and not kg: kg = round(lb * 0.453592, 1)
    if kg and not lb: lb = round(kg / 0.453592, 1)
    return (str(lb) if lb else None, str(kg) if kg else None)


def parse_reach(text):
    if not text:
        return None, None
    inches = cm = None
    m = IN_RE.search(text)
    if m: inches = float(m.group(1))
    m2 = CM_RE.search(text)
    if m2: cm = float(m2.group(1))
    if inches and not cm: cm = round(inches * 2.54, 1)
    if cm and not inches: inches = round(cm / 2.54, 1)
    return (str(inches) if inches else None, str(cm) if cm else None)


def build_profile(name, refresh, sleep):
    out = {"query_name": name, "wiki_matched": False, "wiki_url": None}
    candidates = wiki_search(name, refresh=refresh)
    time.sleep(sleep)
    pick = fuzzy_pick(name, candidates)
    if not pick:
        out["match_reason"] = "no_search_hit"
        return out
    page = wiki_page(pick["title"], refresh=refresh)
    time.sleep(sleep)
    ok, reasons = is_ufc_fighter(page)
    out["match_reason"] = json.dumps(reasons)
    if not ok:
        return out
    info = parse_infobox(page["wikitext"])
    out.update(info)
    out["wiki_matched"] = True
    out["wiki_title"] = page["title"]
    out["wiki_url"] = f"https://en.wikipedia.org/wiki/{(page['title'] or '').replace(' ', '_')}"
    h_imp, h_cm = parse_height(info.get("wiki_height", ""))
    w_lb, w_kg = parse_weight(info.get("wiki_weight", ""))
    r_in, r_cm = parse_reach(info.get("wiki_reach", ""))
    out["wiki_height_imperial"] = h_imp
    out["wiki_height_cm"] = h_cm
    out["wiki_weight_lb"] = w_lb
    out["wiki_weight_kg"] = w_kg
    out["wiki_reach_in"] = r_in
    out["wiki_reach_cm"] = r_cm
    return out


def _peaks_from_engine(elo_module, fights_csv):
    """Run elo_module.UFCEloEngine on a fights CSV. Returns a DataFrame with
    columns: Fighter, peak_elo, peak_date."""
    fights = pd.read_csv(fights_csv)

    # Auto-normalise common column-name variants to what the engine expects.
    rename = {}
    for c in fights.columns:
        cu = c.upper().replace(" ", "_")
        if cu in ("DATE", "EVENT_DATE", "FIGHT_DATE"):
            rename[c] = "DATE"
        elif cu in ("FIGHTER_A", "FIGHTER1", "RED_FIGHTER", "R_FIGHTER", "FIGHTER"):
            rename[c] = "FIGHTER_A"
        elif cu in ("FIGHTER_B", "FIGHTER2", "BLUE_FIGHTER", "B_FIGHTER", "OPPONENT"):
            rename[c] = "FIGHTER_B"
        elif cu in ("OUTCOME", "RESULT", "WINNER"):
            rename[c] = "OUTCOME"
        elif cu in ("METHOD", "METHOD_OF_VICTORY", "WIN_BY"):
            rename[c] = "METHOD"
        elif cu in ("WEIGHTCLASS", "WEIGHT_CLASS", "DIVISION"):
            rename[c] = "WEIGHTCLASS"
        elif cu == "EVENT":
            rename[c] = "EVENT"
        elif cu == "BOUT":
            rename[c] = "BOUT"
    fights = fights.rename(columns=rename)

    required = {"DATE", "FIGHTER_A", "FIGHTER_B", "OUTCOME", "METHOD", "WEIGHTCLASS"}
    missing = required - set(fights.columns)
    if missing:
        raise ValueError(
            f"Fights CSV missing required columns: {missing}. "
            f"Available after auto-rename: {list(fights.columns)}"
        )

    fights["DATE"] = pd.to_datetime(fights["DATE"], errors="coerce")
    fights = (fights.dropna(subset=["DATE"])
                    .sort_values("DATE")
                    .reset_index(drop=True))

    engine = elo_module.UFCEloEngine()
    engine.run(fights)
    peaks = engine.peaks_dataframe()
    if peaks.empty:
        return peaks
    return peaks.rename(columns={"Peak Elo": "peak_elo",
                                 "Peak Date": "peak_date"})[
        ["Fighter", "peak_elo", "peak_date"]
    ]


def _peaks_from_csv(elo_csv):
    """Read a precomputed Elo CSV. Returns columns: Fighter, peak_elo, peak_date."""
    df = pd.read_csv(elo_csv)
    name_col = next((c for c in df.columns
                     if c.lower() in ("fighter", "name", "fighter_name")), None)
    if name_col is None:
        raise ValueError(f"No fighter name column in {elo_csv}. Columns: {list(df.columns)}")

    peak_col = next((c for c in df.columns
                     if "peak" in c.lower() and "elo" in c.lower()), None)
    elo_col = peak_col or next((c for c in df.columns
                                if c.lower() in ("elo", "rating")), None)
    if elo_col is None:
        raise ValueError(f"No Elo column in {elo_csv}. Columns: {list(df.columns)}")

    date_col = next((c for c in df.columns if "date" in c.lower()), None)
    keep = [name_col, elo_col] + ([date_col] if date_col else [])

    if peak_col:
        out = df[keep].copy()
    else:
        idx = df.groupby(name_col)[elo_col].idxmax()
        out = df.loc[idx, keep].copy()

    rename = {name_col: "Fighter", elo_col: "peak_elo"}
    if date_col:
        rename[date_col] = "peak_date"
    out = out.rename(columns=rename)
    if "peak_date" not in out.columns:
        out["peak_date"] = None
    return out[["Fighter", "peak_elo", "peak_date"]]


def select_top_ufc_peaks(peaks_df, top_n, tott_names):
    """Fuzzy-match Elo names to the tott CSV (UFC-only), then take top N by
    peak Elo. Returns columns: tott_name, peak_elo, peak_date."""
    if peaks_df is None or peaks_df.empty:
        return pd.DataFrame(columns=["tott_name", "peak_elo", "peak_date"])

    tott_norm = {normalize(n): n for n in tott_names}
    tott_keys = list(tott_norm.keys())

    def match(elo_name):
        norm = normalize(elo_name)
        if norm in tott_norm:
            return tott_norm[norm]
        m = process.extractOne(norm, tott_keys, scorer=fuzz.WRatio)
        if m and m[1] >= 85:
            return tott_norm[m[0]]
        return None

    df = peaks_df.copy()
    df["tott_name"] = df["Fighter"].apply(match)
    df = df.dropna(subset=["tott_name"])
    df = (df.sort_values("peak_elo", ascending=False)
            .drop_duplicates(subset=["tott_name"])
            .head(top_n)
            .reset_index(drop=True))
    return df[["tott_name", "peak_elo", "peak_date"]]


def load_tott(csv_path):
    df = pd.read_csv(csv_path)
    rename = {c: TOTT_KEEP[c] for c in df.columns if c in TOTT_KEEP}
    if not any(v == "name" for v in rename.values()):
        for c in df.columns:
            if "fighter" in c.lower() or "name" in c.lower():
                rename[c] = "name"
                break
    df = df.rename(columns=rename)
    df = df[[c for c in df.columns if c in {"name", "csv_height", "csv_weight",
                                            "csv_reach", "csv_stance", "csv_dob"}]]
    df = df.dropna(subset=["name"]).drop_duplicates(subset=["name"]).reset_index(drop=True)
    return df


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("csv", type=Path)
    ap.add_argument("--out", type=Path, default=Path("Fighter_Profiles.csv"))
    ap.add_argument("--limit", type=int, default=None,
                    help="Process only the first N fighters (test run). Omit to process every fighter.")
    ap.add_argument("--all", action="store_true",
                    help="Deprecated; processing every fighter is now the default. Kept for backward compatibility.")
    ap.add_argument("--refresh", action="store_true")
    ap.add_argument("--sleep", type=float, default=1.0)
    ap.add_argument("--top-elo", dest="top_elo", type=int, default=None,
                    help="Process only the top N UFC fighters by peak Elo.")
    ap.add_argument("--elo-module", dest="elo_module", default="elo_engine",
                    help="Python module exposing UFCEloEngine (default: elo_engine).")
    ap.add_argument("--fights-csv", dest="fights_csv", type=Path,
                    default=Path("ufc_fight_stats.csv"),
                    help="Fights CSV consumed by the Elo engine.")
    ap.add_argument("--elo-csv", dest="elo_csv", type=Path,
                    default=Path("fighter_elo.csv"),
                    help="Fallback precomputed Elo CSV if the engine module is unavailable.")
    args = ap.parse_args()

    tott = load_tott(args.csv)
    print(f"Loaded {len(tott)} unique fighters from {args.csv.name}")

    if args.top_elo:
        peaks_df = None

        # Preferred path: import the Elo module and run UFCEloEngine in-process.
        elo_mod = None
        try:
            elo_mod = importlib.import_module(args.elo_module)
        except ImportError:
            elo_mod = None

        if elo_mod is not None and hasattr(elo_mod, "UFCEloEngine"):
            if not args.fights_csv.exists():
                raise SystemExit(
                    f"Fights CSV not found: {args.fights_csv}. "
                    f"Pass --fights-csv pointing at your fights data."
                )
            print(f"Running {args.elo_module}.UFCEloEngine on {args.fights_csv}...")
            peaks_df = _peaks_from_engine(elo_mod, args.fights_csv)

        elif args.elo_csv.exists():
            print(f"Reading precomputed peaks from {args.elo_csv}...")
            peaks_df = _peaks_from_csv(args.elo_csv)

        else:
            raise SystemExit(
                f"Could not obtain Elo data. Either make '{args.elo_module}' "
                f"importable so UFCEloEngine can run on {args.fights_csv}, "
                f"or provide a precomputed Elo CSV at {args.elo_csv}."
            )

        elo_peaks = select_top_ufc_peaks(
            peaks_df, args.top_elo, tott["name"].tolist()
        )
        print(f"Top {len(elo_peaks)} UFC fighters by peak Elo selected.")

        work = tott[tott["name"].isin(elo_peaks["tott_name"])].copy()
        work = work.merge(elo_peaks, left_on="name", right_on="tott_name",
                          how="left").drop(columns=["tott_name"])
    else:
        # Default: every fighter in the tott CSV. --limit N restricts to a
        # test run on the first N rows. --all is now a no-op kept for
        # backward compatibility.
        work = tott.head(args.limit) if args.limit else tott

    print(f"Processing {len(work)} fighters...")

    profiles = []
    for name in tqdm(work["name"].tolist(), desc="Wikipedia"):
        profiles.append(build_profile(name, refresh=args.refresh, sleep=args.sleep))

    wiki_df = pd.DataFrame(profiles)
    merged = work.merge(wiki_df, left_on="name", right_on="query_name", how="left")
    merged.drop(columns=["query_name"], inplace=True, errors="ignore")

    def coalesce(a, b):
        return a if pd.notna(a) and str(a).strip() else b

    merged["height_final"] = [coalesce(c, w) for c, w in zip(merged.get("csv_height"), merged.get("wiki_height_imperial"))]
    merged["weight_final"] = [coalesce(c, w) for c, w in zip(merged.get("csv_weight"), merged.get("wiki_weight_lb"))]
    merged["reach_final"] = [coalesce(c, w) for c, w in zip(merged.get("csv_reach"), merged.get("wiki_reach_in"))]
    merged["stance_final"] = [coalesce(c, w) for c, w in zip(merged.get("csv_stance"), merged.get("wiki_stance"))]
    merged["dob_final"] = [coalesce(c, w) for c, w in zip(merged.get("csv_dob"), merged.get("wiki_birth_date"))]

    # --top-elo: drop unmatched-on-Wikipedia rows and sort alphabetically.
    if args.top_elo:
        merged = merged[merged["wiki_matched"].fillna(False)].copy()
        merged = merged.sort_values("name", kind="stable").reset_index(drop=True)

    merged.to_csv(args.out, index=False)
    matched = int(merged["wiki_matched"].fillna(False).sum())
    print(f"Wrote {args.out}  ({matched}/{len(merged)} matched on Wikipedia)")
    return 0


if __name__ == "__main__":
    sys.exit(main())